// Objective-C API for talking to JimMobileSDK/jimsdk Go package.
//   gobind -lang=objc -prefix=Go JimMobileSDK/jimsdk
//
// File is generated by gobind. Do not edit.

#ifndef __GoJimsdk_H__
#define __GoJimsdk_H__

#include <Foundation/Foundation.h>
#include "GoUniverse.h"

@class GoJimsdkClient;
@class GoJimsdkRegisterParams;
@class GoJimsdkRegisterResponse;
@class GoJimsdkVerifyEmailResponseData;
@protocol GoJimsdkVerifyEmailResponseListener;
@class GoJimsdkVerifyEmailResponseListener;

@interface GoJimsdkClient : NSObject {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (NSString*)clusterURL;
- (void)setClusterURL:(NSString*)v;
- (long)appID;
- (void)setAppID:(long)v;
- (NSString*)jimAppID;
- (void)setJimAppID:(NSString*)v;
- (NSString*)jimAppSecret;
- (void)setJimAppSecret:(NSString*)v;
- (int64_t)serverTimestampDiff;
- (void)setServerTimestampDiff:(int64_t)v;
- (GoJimsdkRegisterResponse*)sendRegister:(GoJimsdkRegisterParams*)params;
- (GoJimsdkVerifyEmailResponseData*)sendVerifyEmail:(NSString*)email;
- (void)sendVerifyEmailAsync:(NSString*)email listener:(id<GoJimsdkVerifyEmailResponseListener>)listener;
@end

@interface GoJimsdkRegisterParams : NSObject {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (long)appID;
- (void)setAppID:(long)v;
- (NSString*)username;
- (void)setUsername:(NSString*)v;
- (NSString*)password;
- (void)setPassword:(NSString*)v;
- (NSString*)phone;
- (void)setPhone:(NSString*)v;
- (NSString*)email;
- (void)setEmail:(NSString*)v;
- (NSString*)weixinOpenID;
- (void)setWeixinOpenID:(NSString*)v;
- (NSString*)qqOpenID;
- (void)setQqOpenID:(NSString*)v;
- (NSString*)sinaUID;
- (void)setSinaUID:(NSString*)v;
- (NSString*)facebookID;
- (void)setFacebookID:(NSString*)v;
- (NSString*)twitterID;
- (void)setTwitterID:(NSString*)v;
- (NSString*)linkedInID;
- (void)setLinkedInID:(NSString*)v;
- (NSString*)verificationCode;
- (void)setVerificationCode:(NSString*)v;
@end

@interface GoJimsdkRegisterResponse : NSObject {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (int64_t)id_;
- (void)setID:(int64_t)v;
- (NSString*)username;
- (void)setUsername:(NSString*)v;
- (int64_t)registerTime;
- (void)setRegisterTime:(int64_t)v;
- (NSString*)email;
- (void)setEmail:(NSString*)v;
- (BOOL)emailChecked;
- (void)setEmailChecked:(BOOL)v;
- (NSString*)phone;
- (void)setPhone:(NSString*)v;
- (BOOL)phoneChecked;
- (void)setPhoneChecked:(BOOL)v;
@end

@interface GoJimsdkVerifyEmailResponseData : NSObject {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (BOOL)result;
- (void)setResult:(BOOL)v;
@end

@protocol GoJimsdkVerifyEmailResponseListener
- (void)onFailure:(NSString*)err;
- (void)onSuccess:(GoJimsdkVerifyEmailResponseData*)respData;
@end

FOUNDATION_EXPORT BOOL GoJimsdkNewClient(NSString* clusterURL, long appID, NSString* jimAppID, NSString* jimAppSecret, GoJimsdkClient** ret0_, NSError** error);

FOUNDATION_EXPORT GoJimsdkRegisterParams* GoJimsdkNewRegisterParams();

@class GoJimsdkVerifyEmailResponseListener;

@interface GoJimsdkVerifyEmailResponseListener : NSObject <GoJimsdkVerifyEmailResponseListener> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)onFailure:(NSString*)err;
- (void)onSuccess:(GoJimsdkVerifyEmailResponseData*)respData;
@end

#endif
