// Objective-C API for talking to JimMobileSDK/jimsdk Go package.
//   gobind -lang=objc -prefix=Go JimMobileSDK/jimsdk
//
// File is generated by gobind. Do not edit.

#ifndef __GoJimsdk_H__
#define __GoJimsdk_H__

#include <Foundation/Foundation.h>
#include "GoUniverse.h"

@class GoJimsdkClient;

@interface GoJimsdkClient : NSObject {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (NSString*)clusterURL;
- (void)setClusterURL:(NSString*)v;
- (NSString*)appID;
- (void)setAppID:(NSString*)v;
- (NSString*)jimAppID;
- (void)setJimAppID:(NSString*)v;
- (NSString*)jimAppSecret;
- (void)setJimAppSecret:(NSString*)v;
- (int64_t)serverTimestamp;
- (void)setServerTimestamp:(int64_t)v;
@end

FOUNDATION_EXPORT BOOL GoJimsdkNewClient(NSString* clusterURL, NSString* appID, NSString* jimAppID, NSString* jimAppSecret, GoJimsdkClient** ret0_, NSError** error);

#endif
