
// Objective-C API for talking to the following Go packages
//
//	JimMobileSDK/jimsdk
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Jimsdk_H__
#define __Jimsdk_H__

#include "GoJimsdk.h"
#include "GoUniverse.h"

#endif
